<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="user-PC" name="com.crm.qa.testcases.LoginPageTest" tests="4" failures="1" timestamp="21 Sep 2018 23:08:49 GMT" time="59.197" errors="0">
  <testcase name="validateCreateNewContact" time="14.009" classname="com.crm.qa.testcases.LoginPageTest"/>
  <testcase name="validateCreateNewContact" time="15.632" classname="com.crm.qa.testcases.LoginPageTest"/>
  <testcase name="validateCreateNewContact" time="17.712" classname="com.crm.qa.testcases.LoginPageTest"/>
  <testcase name="returnDateMismatch" time="11.844" classname="com.crm.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="Select Flight page is not diaplayed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Select Flight page is not diaplayed expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertFalse(Assert.java:62)
	at com.crm.qa.pages.FlightFinderPage.goToFlightPage(FlightFinderPage.java:107)
	at com.crm.qa.testcases.LoginPageTest.returnDateMismatch(LoginPageTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- returnDateMismatch -->
</testsuite> <!-- com.crm.qa.testcases.LoginPageTest -->
